### PR TITLE
Feature MyEMSL Metadata

### PR DESCRIPTION
**Pull request by markborkum**
### Description

* Adds new Haskell package for Pacifica Metadata Services type definitions.
* Adds new Haskell package for interaction with Pacifica Metadata Services via cURL.
* Adds configuration via JSON document.
* Adds monad transformer for "applications."
* Executes SQL SELECT statement over very large database tables (using sliding window algorithm).
* Adds framework for file path patterns and rules.

### Issues Resolved

None

### Check List

- [x] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by markborkum** [comment]
Merged branch. Resolved conflicts. See https://github.com/pacifica/pacifica-robinhood-migration/pull/13/commits/b33093332bae7d41a6384272bb8e9b87763cbe0e.

Had to resolve conflicts in `pacifica-robinhood-migration/src/Pacifica/Robinhood/Migration/Conversions.hs` (file that is, eventually, deleted by this PR).

**Comment by dmlb2000** [comment]
I know references to `App.hs` may not be the actual thing but more of a fixture main for that module but code climate is referencing a parse error in ` pacifica-robinhood-migration/src/Pacifica/Robinhood/Migration/App.hs` is that correct?

**Comment by markborkum** [comment]
The "Parse error" is incorrect. The code is syntactically-valid Haskell that is accepted by the compiler. This may be another symptom of the current version of Code Climate using an old version of HLint.

**Review by dmlb2000 — APPROVED** [review]
Looks good

**Pull request merged**
